title: a wave press
email: info@awavepress.com
description: a wave press is a private press with an emphasis on experimental work in and around music and sound.
url: "https://awavepress.com/"
twitter_username: awavepress
instagram_username: awavepress

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
